class APIStatusMessage:
    #SUCCESS
    OK = "OK"
    NO_RESULTS = "NO_RESULTS"

    #FAILURES    
    QUOTA_EXCEEDED = "QUOTA_EXCEEDED"
    WRONG_CREDENTIALS = "WRONG_CREDENTIALS"
    INVALID_FORMAT = "INVALID_FORMAT"
    ERROR = "ERROR"